[build]
  command = "npm run build"
  publish = ".next"

[functions]
  included_files = ["data/db/schema.sql", "data/db/seeds.sql", "data/subtitles/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
