import fs from 'fs'
const gen = JSON.parse(fs.readFileSync('src/lib/movies.generated.json', 'utf8'))
const list = Array.isArray(gen) ? gen : gen.movies || []
const kd = JSON.parse(fs.readFileSync('src/lib/kdramas.json', 'utf8'))
const w = JSON.parse(fs.readFileSync('src/lib/western.json', 'utf8'))
console.log('generated:', list.length, '| kdramas:', kd.length, '| western:', w.length)
const byCat = {}
for (const x of list) byCat[x.category] = (byCat[x.category] || 0) + 1
console.log('generated by category:', JSON.stringify(byCat))
// hardcoded movies.js slugs
const src = fs.readFileSync('src/lib/movies.js', 'utf8')
const slugs = [...src.matchAll(/slug:\s*'([^']+)'/g)].map((m) => m[1])
console.log('hardcoded movie slugs:', slugs.length)
// types present?
const types = {}
for (const x of list) types[x.type || 'none'] = (types[x.type || 'none'] || 0) + 1
console.log('generated types:', JSON.stringify(types))
console.log('kdrama sample:', JSON.stringify(kd[0]).slice(0, 300))
console.log('western sample:', JSON.stringify(w[0]).slice(0, 300))
