import { writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const d = (title, year, rating, genres, episodes, runtime, director, cast, plot) =>
  ({ title, year, rating, genres, episodes, runtime, director, cast, plot });

const kdramas = [
d("Queen of Tears",2024,8.5,["Romance","Drama","Comedy"],16,"1h 25m","Jang Young-woo",["Kim Soo-hyun","Kim Ji-won"],"The turbulent love story between a chaebol heiress and an ordinary man as they face a life-threatening crisis."),
d("Lovely Runner",2024,8.5,["Romance","Fantasy","Comedy"],16,"1h 10m","Yoon Jong-ho",["Byeon Woo-seok","Kim Hye-yoon"],"A disabled fangirl travels back in time to save her idol from a tragic fate changing both their destinies."),
d("Doctor Slump",2024,8.0,["Romance","Comedy","Medical"],16,"1h 10m","Oh Hyun-jong",["Park Hyung-sik","Park Shin-hye"],"Two former high school rivals both now burned-out doctors find healing and romance while being neighbors."),
d("Marry My Husband",2024,8.2,["Romance","Fantasy","Thriller"],16,"1h 10m","Park Won-wook",["Park Min-young","Na In-woo","Lee Yi-kyung"],"A terminally ill woman gets a chance to travel back in time and change her destiny by marrying someone else."),
d("Captivating the King",2024,7.8,["Historical","Romance","Drama"],16,"1h 15m","Kim Sang-ho",["Jo Jung-suk","Shin Se-kyung"],"A Joseon king falls for a woman whose identity and motives are shrouded in mystery."),
d("The Impossible Heir",2024,7.5,["Thriller","Drama"],12,"1h 05m","Lee Won-sub",["Lee Jae-wook","Choo Young-woo","Hong Soo-hyun"],"A man with a traumatic past and a charismatic friend scheme to infiltrate a powerful conglomerate."),
d("Hierarchy",2024,7.3,["Drama","Romance","Thriller"],7,"1h 05m","Bae Hyun-jin",["Ro Jong-hyuk","Jung Chaeyeon","Lee Chae-min"],"At an elite high school controlled by wealthy families a scholarship student shakes up the social order."),
d("The Midnight Romance in Hagwon",2024,7.5,["Romance","Drama"],16,"1h 10m","Ahn Pan-seok",["Wi Ha-jun","Jung Ryeo-won"],"A former student returns to his cram school as an instructor and reconnects with his old teacher."),
d("Connection",2024,7.6,["Crime","Thriller","Drama"],14,"1h 10m","Kim Myung-woo",["Ji Sung","Jeon Yeo-been"],"A veteran detective and a reporter team up to investigate murders connected by a drug ring."),
d("The Atypical Family",2024,7.7,["Romance","Fantasy","Drama"],12,"1h 10m","Cho Hyun-taek",["Jang Ki-yong","Chun Woo-hee"],"A family that once had supernatural powers loses them until a mysterious woman enters their lives."),
d("Flex X Cop",2024,7.6,["Action","Comedy","Crime"],16,"1h 10m","Kim Won-seok",["Ahn Bo-hyun","Park Ji-hyun"],"A chaebol spoiled son becomes a flashy undercover detective clashing with his serious partner."),
d("Wedding Impossible",2024,7.3,["Romance","Comedy","Drama"],12,"1h 10m","Kwon Young-il",["Jeon Jong-seo","Kim Do-hoon"],"An aspiring actress enters a contract marriage with a chaebol heir to help him hide his secret."),
d("Parasyte: The Grey",2024,7.5,["Horror","Action","Sci-Fi"],6,"1h 10m","Yeom Sang-ho",["Jeon So-ni","Koo Kyo-hwan","Lee Jung-hyun"],"Parasitic aliens invade Korea and a woman partially infected fights to stop them."),
d("Missing Crown Prince",2024,7.4,["Historical","Romance","Comedy"],20,"1h 10m","Kim Jung-min",["Suho","Hong Ye-ji"],"The crown prince of Joseon falls for the daughter of a physician who kidnaps him."),
d("Wonderful World",2024,7.6,["Drama","Thriller","Mystery"],14,"1h 10m","Lee Dong-yoon",["Kim Nam-joo","Cha Eun-woo"],"A woman seeks revenge after losing her son while a medical student with a troubled past gets involved."),
d("A Shop for Killers",2024,7.7,["Action","Thriller","Drama"],8,"1h 05m","Lee Kwon",["Ji Chang-wook","Kim Hye-jun"],"A young woman inherits a mysterious shop and discovers it is a front for a deadly operation."),
d("Moving",2023,8.5,["Action","Fantasy","Drama"],20,"1h 20m","Park In-je",["Jo In-sung","Han Hyo-joo"],"Parents with hidden superpowers protect their children who are beginning to manifest abilities."),
d("Extraordinary Attorney Woo",2023,8.7,["Drama","Comedy"],16,"1h 15m","Yoo In-shik",["Park Eun-bin","Kang Tae-oh","Kang Ki-young"],"A brilliant attorney on the autism spectrum uses her unique perspective to solve cases."),
d("The Glory",2023,8.1,["Thriller","Drama"],16,"1h 10m","Ahn Gil-ho",["Song Hye-kyo","Lim Ji-yeon","Lee Do-hyun"],"A woman scarred by school bullying meticulously plots revenge against her tormentors."),
d("My Dearest",2023,8.2,["Historical","Romance","Drama"],20,"1h 10m","Kim Cheol-kyu",["Namkoong Min","Ahn Eun-jin"],"In the late Joseon era a scholar and a woman navigate love amid war and social upheaval."),
d("Bloodhounds",2023,8.0,["Action","Crime","Drama"],8,"1h 10m","Kim Jin-min",["Woo Do-hwan","Lee Sang-yi"],"Three young boxers get entangled with a ruthless loan shark who preys on the vulnerable."),
d("Mask Girl",2023,7.8,["Thriller","Dark Comedy","Drama"],7,"1h 05m","Han Dong-wook",["Go Hyun-jung","Nana","Ahn Jae-hong"],"An office worker moonlights as a masked online streamer and a series of murders follows."),
d("Castaway Diva",2023,7.8,["Romance","Drama","Music"],12,"1h 10m","Oh Choong-hwan",["Park Eun-bin","Kim Hyo-jin"],"A woman stranded on an island for 15 years returns to pursue her dream of becoming a singer."),
d("King the Land",2023,7.8,["Romance","Comedy"],16,"1h 20m","Im Hyun-wook",["Lee Jun-ho","Im Yoon-ah"],"A chaebol heir who cannot stand fake smiles falls for a hotel employee with a genuine smile."),
d("Alchemy of Souls",2023,8.5,["Fantasy","Romance","Historical"],20,"1h 20m","Park Joon-hwa",["Lee Jae-wook","Go Youn-jung","Hwang Min-hyun"],"In a world where souls are swapped a powerful assassin spirit inhabits a blind woman."),
d("The Uncanny Counter Season 2",2023,7.6,["Action","Fantasy","Thriller"],12,"1h 10m","Yoo Seon-dong",["Jo Byung-gyu","Yoo Jun-sang","Kim Se-jeong"],"The demon hunters face new and more powerful evil spirits."),
d("Twenty-Five Twenty-One",2022,8.3,["Romance","Drama"],16,"1h 15m","Jung Ji-hyun",["Nam Joo-hyuk","Kim Tae-ri"],"A fencer and a struggling reporter find strength and love as they grow from ages twenty-five to twenty-one."),
d("Business Proposal",2022,8.0,["Romance","Comedy"],12,"1h 10m","Park Sun-ho",["Ahn Hyo-seop","Kim Se-jeong"],"A woman goes on a blind date in place of her friend only to discover her date is the CEO."),
d("Our Beloved Summer",2022,8.1,["Romance","Drama"],16,"1h 10m","Kim Yoon-jin",["Choi Woo-shik","Kim Da-mi"],"A documentary about a bickering ex-couple goes viral forcing them to confront unresolved feelings."),
d("Forecasting Love and Weather",2022,7.6,["Romance","Comedy","Drama"],16,"1h 10m","Cha Young-hoon",["Park Min-young","Song Kang"],"Colleagues at the Korea Meteorological Administration navigate the unpredictable weather of love."),
d("Tracer",2022,7.8,["Action","Thriller","Drama"],16,"1h 05m","Lee Won-sub",["Im Si-wan","Go Ah-sung"],"A mysterious tax investigator joins the National Tax Service to uncover corruption."),
d("Thirty-Nine",2022,7.5,["Drama","Friendship"],12,"1h 10m","Kim Sang-ho",["Son Ye-jin","Jeon Mi-do"],"Three women on the verge of turning forty navigate friendship love and a terminal illness."),
d("Under the Queen Umbrella",2022,8.1,["Historical","Drama","Comedy"],16,"1h 10m","Kim Sang-hyung",["Kim Hye-soo","Choi Won-young"],"A queen mother raises her troublemaking sons into worthy princes in the Joseon court."),
d("Shooting Stars",2022,7.7,["Romance","Comedy","Drama"],16,"1h 05m","Lee Soo-hyun",["Lee Sung-kyung","Kim Young-dae"],"A publicist and the top actor she manages bicker constantly while hiding their true feelings."),
d("Bloody Heart",2022,7.6,["Historical","Romance","Drama"],16,"1h 10m","Choi Won-seok",["Lee Joon","Kang Han-na"],"In a reimagined Joseon dynasty a king and a woman are caught in a brutal power struggle."),
d("One Dollar Lawyer",2022,7.7,["Legal","Comedy","Drama"],12,"1h 10m","Kim Jae-hyun",["Namkoong Min","Kim Ji-eun"],"A brilliant lawyer who only charges one dollar takes on cases the rich try to bury."),
d("The Golden Spoon",2022,7.4,["Fantasy","Drama","Thriller"],16,"1h 10m","Song Hyun-wook",["Yook Sung-jae","Lee Jong-won"],"A poor student obtains a magical golden spoon that allows him to swap lives with a wealthy classmate."),
d("Cheer Up",2022,7.5,["Romance","Comedy","Drama"],16,"1h 10m","Han Tae-sung",["Han Ji-hyun","Bae In-hyuk"],"A university cheerleader navigates campus romance secrets and the dark underbelly of cheerleading."),
d("Little Women",2022,7.7,["Thriller","Drama","Mystery"],12,"1h 10m","Kim Hee-won",["Kim Go-eun","Nam Ji-hyun","Park Ji-hu"],"Three sisters from a poor family get entangled with one of Korea wealthiest families."),
d("Anna",2022,7.5,["Drama","Thriller"],8,"1h 05m","Lee Joo-young",["Bae Suzy","Jung Sun-hwa"],"A woman assumes another identity and builds a successful life based on lies."),
d("Bad Prosecutor",2022,7.5,["Legal","Comedy","Thriller"],12,"1h 05m","Kim Yong-woo",["D.O.","Lee Se-hee"],"A con-artist prosecutor uses unorthodox methods to take down corrupt officials."),
d("Shadow Detective",2022,7.7,["Crime","Thriller","Drama"],8,"1h 05m","Park Hyun-suk",["Lee Sung-min","Kyung Soo-jin"],"A veteran detective is contacted by a killer who threatens to frame him for future crimes."),
d("The Law Cafe",2022,7.5,["Romance","Comedy","Legal"],16,"1h 10m","Lee Soo-hyun",["Lee Seung-gi","Lee Se-young"],"A quirky lawyer and his former colleague open a law-themed cafe and navigate romance."),
d("Poong the Joseon Psychiatrist",2022,7.5,["Historical","Comedy","Drama"],20,"1h 05m","Lee Eung-bok",["Kim Min-jae","Kim Hyang-gi"],"A royal physician turns to psychiatry after a scandal and opens a practice in Hanyang."),
d("Eve",2022,7.3,["Romance","Thriller","Drama"],16,"1h 10m","Park Bong-sub",["Seo Yea-ji","Park Byung-eun"],"A woman executes a 13-year revenge plan against a conglomerate family."),
d("Why Her?",2022,7.5,["Legal","Drama","Romance"],16,"1h 10m","Park Soo-jin",["Seo Hyun-jin","Hwang In-yeop"],"A cold-hearted lawyer is demoted and falls for a law student connected to her past."),
d("Crazy Love",2022,7.4,["Romance","Comedy","Thriller"],12,"1h 05m","Kim Jeong-hyun",["Krystal Jung","Kim Jae-wook"],"A top math instructor loses his memory and his secretary pretends to be his fiancee."),
d("Link: Eat Love Kill",2022,7.3,["Romance","Fantasy","Thriller"],16,"1h 10m","Hong Jong-chan",["Yeo Jin-goo","Moon Ga-young"],"A chef suddenly feels the emotions of a stranger and they become entangled in a mystery."),
d("Rookie Cops",2022,7.5,["Action","Drama","Romance"],16,"1h 10m","Kim Byung-soo",["Choi Woo-shik","Kang Daniel"],"Rookies at the police academy navigate training friendship and a dangerous campus mystery."),
d("Racket Boys",2021,7.7,["Comedy","Sports","Drama"],16,"1h 10m","Cho Won-woo",["Tang Jun-sang","Soo Ae"],"A big-city badminton prodigy moves to the countryside to revive a dying junior team."),
d("Taxi Driver",2021,8.1,["Action","Thriller","Drama"],16,"1h 10m","Lee Joon",["Lee Je-hoon","Esom"],"A secret organization offers revenge-for-hire service to victims denied justice."),
d("Hometown Cha-Cha-Cha",2021,8.7,["Romance","Comedy","Drama"],16,"1h 25m","Yoo Je-won",["Shin Min-a","Kim Seon-ho"],"A big-city dentist opens a practice in a seaside village and falls for a jack-of-all-trades."),
d("Vincenzo",2021,8.4,["Action","Comedy","Drama"],20,"1h 25m","Kim Hee-won",["Song Joong-ki","Jeon Yeo-been"],"A Korean-Italian mafia lawyer returns to claim hidden gold and fights for justice."),
d("Squid Game",2021,8.0,["Thriller","Drama","Action"],9,"1h 10m","Hwang Dong-hyuk",["Lee Jung-jae","Park Hae-soo","Wi Ha-jun"],"Cash-strapped players compete in deadly children games for a huge cash prize."),
d("Red Sleeve",2021,8.8,["Historical","Romance","Drama"],17,"1h 20m","Cha Young-hoon",["Lee Jun-ho","Lee Se-young"],"The love story between a royal consort and King Jeongjo of Joseon."),
d("Hospital Playlist Season 2",2021,9.0,["Comedy","Drama"],12,"1h 30m","Shin Won-ho",["Jo Jung-suk","Yoo Yeon-seok","Jung Kyung-ho"],"Five doctor friends continue navigating hospital life and their band journey."),
d("Beyond Evil",2021,8.5,["Thriller","Crime","Drama"],16,"1h 05m","Sim Na-yeon",["Shin Ha-kyun","Yeo Jin-goo"],"A police chief and a detective suspect each other of being a serial killer."),
d("My Name",2021,7.9,["Action","Crime","Thriller"],8,"1h 10m","Kim Jin-min",["Han So-hee","Park Hee-soon"],"A woman joins a crime syndicate and becomes a police mole to find her father killer."),
d("Happiness",2021,7.8,["Thriller","Horror","Drama"],12,"1h 10m","Ahn Gil-ho",["Han Hyo-joo","Park Hyung-sik"],"Residents of an apartment building are locked down after a mysterious disease breaks out."),
d("Inspector Koo",2021,7.8,["Action","Thriller","Comedy"],12,"1h 10m","Lee Won-suk",["Lee Young-ae","Kim Hye-ja"],"An insurance investigator hunts a serial killer targeting insurance scammers."),
d("Doom at Your Service",2021,7.7,["Romance","Fantasy","Drama"],16,"1h 10m","Kwon Young-il",["Seo In-guk","Park Bo-young"],"A woman who has given up on life accidentally summons a cosmic being."),
d("My Roommate Is a Gumiho",2021,7.6,["Romance","Comedy","Fantasy"],16,"1h 10m","Nam Sung-woo",["Jang Ki-yong","Lee Hye-ri"],"A nine-tailed fox accidentally transfers his fox bead to a college student."),
d("Mouse",2021,8.1,["Thriller","Crime","Drama"],20,"1h 05m","Choi Jung-bum",["Lee Seung-gi","Lee Hee-joon"],"A rookie cop and a serial killer son are caught in a deadly game of cat and mouse."),
d("Jirisan",2021,7.5,["Thriller","Mystery","Drama"],16,"1h 20m","Lee Eung-bok",["Jun Ji-hyun","Joo Ji-hoon"],"Rangers at Jirisan National Park investigate mysterious incidents on the mountain."),
d("Mine",2021,7.7,["Drama","Thriller","Mystery"],16,"1h 10m","Lee Na-jung",["Lee Bo-young","Kim Seo-hyung"],"Two daughters-in-law of a powerful chaebol fight to reclaim their identities."),
d("The Veil",2021,7.8,["Action","Thriller","Espionage"],12,"1h 05m","Kim Sung-min",["Namkoong Min","Kim Ji-eun"],"An elite NIS agent who lost his memory returns to find the traitor."),
d("Snowdrop",2021,7.5,["Romance","Drama","Thriller"],16,"1h 20m","Jo Hyun-taek",["Jung Hae-in","Kim Ji-soo"],"A university student shelters a wounded man who turns out to be a North Korean spy."),
d("Navillera",2021,8.5,["Drama","Friendship"],12,"1h 05m","Han Dong-hwa",["Song Il-gook","Park In-hwan"],"A 70-year-old man fulfills his lifelong dream of becoming a ballet dancer."),
d("One the Woman",2021,7.8,["Comedy","Thriller","Romance"],16,"1h 10m","Choi Young-soo",["Lee Ha-nee","Lee Sang-yoon"],"A corrupt prosecutor accidentally switches identities with a chaebol daughter-in-law."),
d("Sell Your Haunted House",2021,7.5,["Comedy","Horror","Drama"],16,"1h 10m","Park Soo-jin",["Jang Na-ra","Jung Young-hae"],"A real estate agent who exorcises haunted houses teams up with a ghost-seeing con artist."),
d("Now We Are Breaking Up",2021,7.3,["Romance","Drama"],16,"1h 10m","Lee Gil-bok",["Song Hye-kyo","Jang Ki-yong"],"A fashion design team leader and a photographer fall in love while navigating breakups."),
d("You Are My Spring",2021,7.6,["Romance","Drama","Thriller"],16,"1h 10m","Cho Hyun-haek",["Seo Hyun-jin","Kim Dong-wook"],"A hotel manager and a psychiatrist find healing through love despite shared childhood trauma."),
d("Nevertheless",2021,7.3,["Romance","Drama"],10,"1h 05m","Kim Ga-ram",["Song Kang","Han So-hee"],"A woman who does not believe in love and a flirtatious man have a complicated relationship."),
d("It Is Okay to Not Be Okay",2020,8.7,["Romance","Drama","Psychological"],16,"1h 20m","Park Shin-woo",["Kim Soo-hyun","Seo Yea-ji"],"A psychiatric ward worker and an antisocial children book author heal each other."),
d("Hospital Playlist",2020,9.0,["Comedy","Drama"],12,"1h 30m","Shin Won-ho",["Jo Jung-suk","Yoo Yeon-seok","Jung Kyung-ho"],"Five doctor friends since medical school navigate hospital life while playing music."),
d("Itaewon Class",2020,8.2,["Drama"],16,"1h 20m","Kim Sung-yoon",["Park Seo-joon","Kim Da-mi"],"An ex-con and his friends fight to make their dreams for their street food business real."),
d("Start-Up",2020,8.0,["Romance","Drama"],16,"1h 20m","Oh Choong-hwan",["Bae Suzy","Nam Joo-hyuk","Kim Seon-ho"],"Aspiring entrepreneurs chase their dreams of launching a start-up in Sandbox."),
d("True Beauty",2020,7.8,["Romance","Comedy","Drama"],16,"1h 10m","Kim Sang-hyeop",["Moon Ga-young","Cha Eun-woo","Hwang In-yeop"],"A high school girl who is a makeup goddess by day hides her bare face and finds love."),
d("The King: Eternal Monarch",2020,7.5,["Romance","Fantasy","Sci-Fi"],16,"1h 25m","Baek Sang-hoon",["Lee Min-ho","Kim Go-eun"],"The Emperor of Korea crosses into a parallel world and falls for a detective."),
d("Record of Youth",2020,7.8,["Romance","Drama"],16,"1h 15m","Ahn Gil-ho",["Park Soo-hyun","Park Bo-gum"],"Two young models navigate the competitive world of entertainment and love."),
d("18 Again",2020,8.3,["Comedy","Fantasy","Drama"],16,"1h 15m","Ha Byung-hoon",["Yoon Sang-hyun","Kim Ha-neul","Lee Do-hyun"],"A man on the verge of divorce becomes his 18-year-old self and sees his family anew."),
d("Penthouse: War in Life",2020,7.8,["Drama","Thriller","Mystery"],43,"1h 15m","Joo Dong-min",["Lee Ji-ah","Kim So-yeon","Eugene"],"Residents of a luxury penthouse engage in murder schemes and revenge."),
d("The Uncanny Counter",2020,7.8,["Action","Fantasy","Thriller"],16,"1h 10m","Yoo Seon-dong",["Jo Byung-gyu","Yoo Jun-sang","Kim Se-jeong"],"Demon hunters disguised as noodle restaurant employees fight evil spirits."),
d("Tale of the Nine Tailed",2020,7.6,["Fantasy","Romance","Action"],16,"1h 10m","Kang Shin-hyo",["Lee Dong-wook","Jo Bo-ah","Kim Bum"],"A nine-tailed fox in the city becomes entangled with a producer of urban legends."),
d("Find Me in Your Memory",2020,7.8,["Romance","Drama","Sci-Fi"],32,"35m","Oh Hyun-jong",["Kim Dong-wook","Moon Ga-young"],"A news anchor with hyperthymesia and an actress with forgotten memories intertwine."),
d("Memorist",2020,7.5,["Sci-Fi","Crime","Thriller"],16,"1h 10m","Kim Hwi",["Yoo Seung-ho","Lee Se-young"],"A detective with memory-reading powers teams up with a genius profiler."),
d("Do Do Sol Sol La La Sol",2020,7.5,["Romance","Comedy","Drama"],16,"1h 10m","Kim Min-kyung",["Go A-ra","Lee Jae-wook"],"An optimistic pianist and a quiet young man find love in a seaside town."),
d("Crash Landing on You",2019,8.7,["Romance","Comedy","Drama"],16,"1h 25m","Lee Jung-hyo",["Hyun Bin","Son Ye-jin"],"A South Korean heiress crash-lands in North Korea and falls in love with an officer."),
d("When the Camellia Blooms",2019,8.3,["Romance","Drama","Thriller"],40,"35m","Cha Young-hwang",["Gong Hyo-jin","Kang Ha-neul"],"A single mother runs a bar facing gossip a serial killer and a persistent policeman."),
d("The Fiery Priest",2019,8.2,["Action","Comedy","Crime"],20,"1h 10m","Lee Myung-woo",["Kim Nam-gil","Honey Lee"],"A priest with anger management issues teams up with detectives to fight corruption."),
d("Vagabond",2019,8.1,["Action","Thriller","Drama"],16,"1h 25m","Yoo In-sik",["Lee Seung-gi","Bae Suzy"],"A stuntman investigates a plane crash uncovering a massive political conspiracy."),
d("Extraordinary You",2019,7.8,["Romance","Fantasy","Comedy"],32,"35m","Kim Sang-hyung",["Kim Hye-yoon","Rowoon","Lee Jae-wook"],"A girl discovers she is a character in a manga and tries to change her fate."),
d("Arthdal Chronicles",2019,7.6,["Fantasy","Drama","Action"],18,"1h 20m","Kim Won-seok",["Jang Dong-gun","Song Joong-ki","Kim Ok-vin"],"In mythical Arth civilizations rise as tribes and powers clash for dominance."),
d("The Tale of Nokdu",2019,8.0,["Historical","Romance","Comedy"],32,"35m","Kim Dong-hwi",["Jang Dong-yoon","Kim So-hyun"],"A man disguises himself as a woman to infiltrate a widow village and uncovers conspiracies."),
d("Doctor Prisoner",2019,7.9,["Thriller","Drama"],32,"35m","Hwang In-hyuk",["Namkoong Min","Kwon Nara"],"A wrongfully imprisoned surgeon becomes a prison doctor and seeks revenge."),
d("Love Alarm",2019,7.3,["Romance","Sci-Fi","Drama"],14,"1h 05m","Lee Na-jung",["Kim So-hyun","Song Kang"],"In a world where an app alerts you when someone nearby loves you a triangle forms."),
d("My Country: The New Age",2019,7.8,["Historical","Action","Drama"],16,"1h 10m","Kim Sang-ho",["Yang Se-jong","Woo Do-hwan"],"Two friends fight on opposite sides during the founding of the Joseon dynasty."),
d("Strangers from Hell",2019,8.0,["Thriller","Horror","Drama"],10,"1h 10m","Lee Chang-hee",["Im Si-wan","Lee Dong-wook"],"A man moves into a creepy apartment building and discovers disturbing neighbors."),
d("Welcome to Waikiki Season 2",2019,7.8,["Comedy","Drama"],16,"1h 10m","Lee Chang-min",["Kim Jung-hyun","Shin Hyun-soo","Moon Ga-young"],"A new group of friends runs a guesthouse navigating comedy and chaos."),
d("Leverage",2019,7.5,["Action","Comedy","Crime"],16,"1h 10m","Nam Sung-woo",["Lee Dong-wook","Jeon Hye-jin"],"A team of ex-con artists becomes vigilantes targeting corrupt elites."),
d("Catch the Ghost",2019,7.5,["Crime","Comedy","Thriller"],16,"1h 10m","Park Shin-woo",["Moon Geun-young","Kim Sun-ho"],"A subway police unit investigates crimes underground while hunting a serial killer."),
d("What's Wrong with Secretary Kim",2018,8.2,["Romance","Comedy"],16,"1h 10m","Park Joon-hwa",["Park Seo-joon","Park Min-young"],"A narcissistic vice chairman panics when his secretary announces her resignation."),
d("Sky Castle",2018,8.5,["Drama","Satire"],20,"1h 10m","Cho Hyun-taek",["Yum Jung-ah","Lee Tae-ran"],"Elite families go to extreme lengths for their children success in exams."),
d("Mr. Sunshine",2018,8.9,["Historical","Romance","Action","Drama"],24,"1h 25m","Lee Eung-bok",["Lee Byung-hun","Kim Tae-ri","Yoo Yeon-seok"],"A Korean boy escapes to America returns as a Marine officer and falls for an independence fighter."),
d("My ID Is Gangnam Beauty",2018,7.5,["Romance","Comedy","Drama"],16,"1h 10m","Choi Soo-young",["Im Soo-hyang","Cha Eun-woo"],"A woman who gets plastic surgery finds university life and love unexpected."),
d("The Smile Has Left Your Eyes",2018,8.1,["Romance","Drama","Thriller"],16,"1h 10m","Yoo Je-won",["Seo In-guk","Jung So-min"],"A mysterious man with a dark past falls for a bright-spirited woman."),
d("100 Days My Prince",2018,7.8,["Historical","Romance","Comedy"],16,"1h 15m","Kim Won-seok",["D.O.","Nam Ji-hyun"],"The crown prince loses his memory and lives as a commoner for 100 days."),
d("Life on Mars",2018,8.1,["Sci-Fi","Crime","Drama"],16,"1h 10m","Lee Chung-hyo",["Jung Kyung-ho","Park Sung-woong"],"A 2018 detective falls into a coma and wakes up in 1988 to solve a murder."),
d("Lawless Lawyer",2018,7.8,["Action","Legal","Drama"],16,"1h 10m","Ahn Tae-ho",["Lee Joon-gi","Seo Ye-ji"],"A gangster-turned-lawyer fights corrupt judges and a powerful city ruler."),
d("Are You Human?",2018,7.6,["Sci-Fi","Romance","Action"],32,"35m","Cha Young-hoon",["Seo Kang-joon","Gong Seung-yeon"],"A humanoid robot takes the place of his comatose human counterpart."),
d("Come and Hug Me",2018,7.8,["Romance","Thriller","Drama"],32,"35m","Choi Jung-bum",["Jang Ki-yong","Jin Ki-joo"],"The son of a serial killer and a victim daughter find each other again as adults."),
d("Suits",2018,7.7,["Legal","Drama","Comedy"],16,"1h 10m","Kim Jin-woo",["Jang Dong-gun","Park Hyung-sik"],"A top lawyer hires a brilliant dropout with a photographic memory."),
d("Something in the Rain",2018,7.8,["Romance","Drama"],16,"1h 10m","Ahn Pan-seok",["Son Ye-jin","Jung Hae-in"],"An older woman falls for her best friend younger brother despite societal pressure."),
d("The Beauty Inside",2018,7.8,["Romance","Fantasy","Drama"],16,"1h 10m","Song Hyun-wook",["Seo Hyun-jin","Lee Min-ki"],"A woman falls for a man who changes into a different person every few weeks."),
d("Terius Behind Me",2018,7.8,["Romance","Action","Comedy"],32,"35m","Park Sang-hyun",["So Ji-sub","Jung In-sun"],"A former NIS agent protects his neighbor and her children from a conspiracy."),
d("The Hymn of Death",2018,8.3,["Historical","Romance","Melodrama"],6,"35m","Park Soo-jin",["Lee Jong-suk","Shin Hye-sun"],"A soprano singer and a playwright fall in love during the Japanese occupation."),
d("About Time",2018,7.5,["Romance","Fantasy","Drama"],16,"1h 10m","Kim Hyung-il",["Lee Sang-yoon","Lee Se-young"],"A musical actress who sees lifespans falls for a man with time-stopping power."),
d("Miss Hammurabi",2018,7.7,["Legal","Drama","Romance"],16,"1h 05m","Kwak Jung-hwan",["Go A-ra","L"],"Three judges with different philosophies navigate law and justice."),
d("Prison Playbook",2017,8.8,["Comedy","Drama"],16,"1h 30m","Shin Won-ho",["Park Hae-il","Jung Kyung-ho"],"A baseball player adjusts to life behind bars with his doctor friend and cellmates."),
d("Fight for My Way",2017,8.1,["Romance","Comedy","Drama"],16,"1h 15m","Lee Na-jung",["Park Seo-joon","Kim Ji-won"],"Four friends chase dreams and navigate the transition from youth to adulthood."),
d("While You Were Sleeping",2017,8.4,["Romance","Fantasy","Drama"],32,"35m","Oh Choong-hwan",["Lee Jong-suk","Bae Suzy"],"A woman sees tragic events in dreams and a prosecutor works to prevent them."),
d("Stranger",2017,8.6,["Crime","Thriller","Drama"],16,"1h 10m","Ahn Gil-ho",["Cho Seung-woo","Bae Doona"],"A prosecutor and detective investigate corruption and a serial murder case."),
d("Strong Girl Bong-soon",2017,8.0,["Comedy","Fantasy","Action"],16,"1h 10m","Lee Hyung-min",["Park Bo-young","Park Hyung-sik"],"A tiny woman with superhuman strength becomes a bodyguard for a CEO."),
d("Suspicious Partner",2017,8.0,["Romance","Comedy","Thriller"],32,"35m","Park Sun-ho",["Ji Chang-wook","Nam Ji-hyun"],"A prosecutor and detective become suspects in a murder case."),
d("W",2017,7.9,["Romance","Fantasy","Thriller"],16,"1h 10m","Jung Dae-yoon",["Lee Jong-suk","Han Hyo-joo"],"A surgeon gets pulled into a webtoon world and falls for the main character."),
d("Tunnel",2017,8.1,["Crime","Fantasy","Thriller"],16,"1h 10m","Shin Yong-hwi",["Choi Jin-hyuk","Yoon Hyun-min"],"A detective from 1986 travels to the present to solve the same serial murder case."),
d("Chief Kim",2017,7.8,["Comedy","Drama"],20,"1h 10m","Lee Jae-sang",["Namkoong Min","Nam Sang-mi"],"A corrupt accountant joins a company to embezzle but becomes an unlikely hero."),
d("Save Me",2017,8.0,["Thriller","Horror","Drama"],16,"1h 05m","Kim Sung-soo",["Ok Taec-yeon","Seo Ye-ji"],"Four young men try to save a woman from a dangerous religious cult."),
d("Money Flower",2017,8.1,["Drama","Thriller"],30,"35m","Kim Hee-won",["Jang Hyuk","Shin Eun-kyung"],"A man seduces and destroys a powerful family as revenge for his mother death."),
d("Black",2017,7.8,["Thriller","Fantasy","Crime"],18,"1h 10m","Cha Young-hoon",["Song Seung-heon","Go Ara"],"A grim reaper in a detective body teams up with a woman who can see death."),
d("The Liar and His Lover",2017,7.3,["Romance","Music","Drama"],16,"1h 10m","Kim Choong-yong",["Lee Hyun-woo","Joy"],"A genius composer and a student with a pure voice fall in love."),
d("Man to Man",2017,7.4,["Action","Comedy","Thriller"],16,"1h 05m","Lee Chang-min",["Park Hae-jin","Park Sun-young"],"A special agent goes undercover as a bodyguard to stop an arms dealer."),
d("The Best Hit",2017,7.6,["Comedy","Music","Drama"],32,"35m","Yoon Sung-ho",["Kim Min-jae","Yoon Shi-yoon"],"A 90s pop star resurfaces 20 years later struggling to adapt."),
d("Witchs Court",2017,7.6,["Legal","Drama","Romance"],16,"1h 10m","Kim Yoon-jin",["Yoon Se-ah","Jung Ryeo-won"],"A ruthless prosecutor is demoted to the sex crimes unit."),
d("Weightlifting Fairy Kim Bok-joo",2016,8.2,["Romance","Comedy","Sports"],16,"1h 10m","Oh Hyun-jong",["Nam Joo-hyuk","Lee Sung-kyung"],"A weightlifter navigates university life and first love with a swimmer."),
d("Goblin",2016,8.6,["Romance","Fantasy","Drama"],16,"1h 20m","Lee Eung-bok",["Gong Yoo","Kim Go-eun","Lee Dong-wook"],"An immortal goblin meets a girl who claims to be the Goblin Bride."),
d("Descendants of the Sun",2016,8.2,["Romance","Drama","Action"],16,"1h 25m","Lee Eung-bok",["Song Joong-ki","Song Hye-kyo"],"A special forces captain and a surgeon fall in love on a peacekeeping mission."),
d("Signal",2016,8.7,["Thriller","Crime","Fantasy"],16,"1h 15m","Kim Won-seok",["Lee Je-hoon","Kim Hye-soo"],"A profiler communicates with a detective in the past through a walkie-talkie."),
d("Moon Lovers: Scarlet Heart Ryeo",2016,8.3,["Romance","Fantasy","Historical"],20,"1h 10m","Kim Kyu-tae",["Lee Joon-gi","IU"],"A modern woman is transported to the Goryeo dynasty entangled with princes."),
d("The Legend of the Blue Sea",2016,8.0,["Romance","Fantasy","Comedy"],20,"1h 10m","Jo Soo-won",["Jun Ji-hyun","Lee Min-ho"],"A mermaid follows her love from Joseon to modern-day Seoul."),
d("Another Miss Oh",2016,8.2,["Romance","Comedy","Drama"],18,"1h 10m","Song Hyun-wook",["Eric Mun","Seo Hyun-jin"],"Two women named Oh and the men who love them are entangled in misunderstandings."),
d("Doctors",2016,7.8,["Romance","Drama"],30,"35m","Oh Choong-hwan",["Park Shin-hye","Kim Rae-won"],"A troubled girl transforms into a neurosurgeon and reunites with her teacher."),
d("Uncontrollably Fond",2016,7.6,["Romance","Drama"],20,"1h 10m","Park Hyun-suk",["Kim Woo-bin","Bae Suzy"],"A top actor and a producer reunite but he hides a terminal illness."),
d("The K2",2016,8.2,["Action","Romance","Thriller"],16,"1h 10m","Kwak Jung-hwan",["Ji Chang-wook","Im Yoon-ah"],"An abandoned soldier becomes a bodyguard entangled in political games."),
d("Dear Fair Lady Gong Shim",2016,7.6,["Romance","Comedy"],20,"1h 10m","Nam Tae-wook",["Namkoong Min","Oh Yeon-seo"],"A lazy older sister and a mysterious rich young man bicker their way to love."),
d("Monster",2016,7.6,["Thriller","Crime","Drama"],50,"1h 05m","Jang Tae-yoo",["Kang Ji-hwan","Soo Ae"],"A detective hunts the serial killer who murdered his wife and daughter."),
d("One More Happy Ending",2016,7.3,["Romance","Comedy"],16,"1h 10m","Kwon Sung-chan",["Jang Nara","Jung Kyung-ho"],"A divorced former idol singer navigates second chances at love."),
d("Kill Me Heal Me",2015,8.5,["Romance","Comedy","Drama"],20,"1h 15m","Kim Dae-jin",["Ji Sung","Hwang Jung-eum","Park Seo-joon"],"A chaebol heir with dissociative identity disorder falls for his psychiatrist."),
d("Reply 1988",2015,9.2,["Comedy","Drama","Romance"],20,"1h 30m","Shin Won-ho",["Lee Hyeri","Ryu Jun-yeol","Park Bo-gum"],"Five families in a Seoul neighborhood navigate life and friendship in 1988."),
d("Oh My Ghost",2015,7.9,["Romance","Comedy","Fantasy"],16,"1h 10m","Yoo Je-won",["Park Bo-young","Jo Jung-suk"],"A timid chef is possessed by a ghost who transforms her into a confident cook."),
d("Six Flying Dragons",2015,8.8,["Historical","Drama","Action"],50,"1h 05m","Sin Yoon-ho",["Yoo Ah-in","Shin Se-kyung"],"The story of Prince Lee Bang-won who helped establish the Joseon dynasty."),
d("She Was Pretty",2015,7.7,["Romance","Comedy"],16,"1h 10m","Cho Dong-hoon",["Park Seo-joon","Hwang Jung-eum"],"A former beauty queen reunites with her wealthy childhood friend who does not recognize her."),
d("Twenty Again",2015,7.8,["Romance","Comedy","Drama"],16,"1h 10m","Kim Hyung-shik",["Choi Siwon","Lee Bo-young"],"A 38-year-old housewife gets a chance to relive her college years."),
d("Scholar Who Walks the Night",2015,7.5,["Historical","Fantasy","Romance"],18,"1h 05m","Lee Sung-joon",["Lee Joon-gi","Shin Se-kyung"],"A vampire scholar and a cross-dressing woman find love in Joseon."),
d("Hidden Identity",2015,7.6,["Action","Crime","Thriller"],16,"1h 10m","Kang Shin-hyo",["Kim Bum","Park Sung-woong"],"An undercover detective infiltrates a criminal organization."),
d("Splish Splash Love",2015,7.8,["Romance","Fantasy","Comedy"],2,"1h 25m","Kim Sung-yoon",["Yoon Doo-joon","Kim Seul-gi"],"A high school student time-travels to the Joseon dynasty and meets King Sejong."),
d("My Love from the Star",2014,8.3,["Romance","Fantasy","Comedy"],21,"1h 10m","Jang Tae-yoo",["Jun Ji-hyun","Kim Soo-hyun"],"An alien from the Joseon Dynasty falls in love with a top actress in modern Seoul."),
d("Pinocchio",2014,8.1,["Romance","Drama","Comedy"],20,"1h 10m","Cho Soo-won",["Lee Jong-suk","Park Shin-hye"],"A man destroyed by false news becomes a reporter alongside a girl with Pinocchio syndrome."),
d("Healer",2014,8.4,["Romance","Action","Thriller"],20,"1h 10m","Lee Chang-min",["Ji Chang-wook","Park Min-young"],"A night courier gets entangled in a 20-year-old mystery."),
d("Empress Ki",2014,8.2,["Historical","Drama"],51,"1h 05m","Han Hee",["Ha Ji-won","Ji Chang-wook"],"A Korean woman rises from slavery to become Empress of the Yuan Dynasty."),
d("Misaeng: Incomplete Life",2014,8.6,["Drama"],20,"1h 10m","Kim Won-seok",["Im Si-wan","Lee Sung-min"],"A former baduk player navigates the corporate world with determination."),
d("It Is Okay Thats Love",2014,8.3,["Romance","Drama","Psychological"],16,"1h 10m","Kim Kyu-tae",["Jo In-sung","Gong Hyo-jin"],"A radio DJ and a psychiatry resident heal each other emotional scars."),
d("Three Days",2014,7.8,["Thriller","Action","Drama"],16,"1h 10m","Shin Kyung-soo",["Park Yoo-chun","Son Hyun-joo"],"A presidential bodyguard has three days to find the missing president."),
d("Gods Gift: 14 Days",2014,7.9,["Thriller","Fantasy","Drama"],16,"1h 10m","Lee Dong-hoon",["Lee Bo-young","Jo Seung-woo"],"A mother gets 14 days to travel back in time to save her kidnapped daughter."),
d("Fated to Love You",2014,7.7,["Romance","Comedy"],20,"1h 10m","Lee Sang-yeob",["Jang Hyuk","Jang Nara"],"An accidental pregnancy leads a chaebol heir and an ordinary girl into unexpected love."),
d("Doctor Stranger",2014,7.3,["Romance","Medical","Thriller"],20,"1h 10m","Hong Jong-chan",["Lee Jong-suk","Kang Sora"],"A genius doctor who escaped North Korea navigates love and conspiracy."),
d("Bride of the Century",2014,7.4,["Romance","Fantasy","Comedy"],16,"1h 05m","Cha Young-hoon",["Lee Hong-ki","Yang Jin-sung"],"A woman takes on the identity of a chaebol bride and discovers a family curse."),
d("Angel Eyes",2014,7.6,["Romance","Drama","Melodrama"],20,"1h 10m","Park Seung-woo",["Lee Sang-yoon","Ku Hye-sun"],"A blind woman and the detective who loved her as a teenager reunite."),
d("Temptation",2014,7.5,["Romance","Drama","Melodrama"],20,"1h 10m","Park Young-soo",["Kwon Sang-woo","Choi Ji-woo"],"A man makes a dangerous deal to save his company and falls for the woman in the bargain."),
d("I Hear Your Voice",2013,8.4,["Romance","Thriller","Fantasy"],18,"1h 10m","Jo Soo-won",["Lee Jong-suk","Lee Bo-young"],"A mind-reading high school student and a lawyer work together."),
d("The Heirs",2013,7.5,["Romance","Drama"],20,"1h 10m","Kang Shin-hyo",["Lee Min-ho","Park Shin-hye","Kim Woo-bin"],"Heirs to major corporations navigate love and family expectations."),
d("Reply 1994",2013,8.7,["Comedy","Romance","Drama"],21,"1h 30m","Shin Won-ho",["Go Ara","Jung Woo","Yoo Yeon-seok"],"College students live together in a Seoul boarding house in 1994."),
d("Master Sun",2013,7.8,["Romance","Comedy","Fantasy"],17,"1h 10m","Jin Hyuk",["So Ji-sub","Gong Hyo-jin"],"A woman who sees ghosts and a greedy CEO form an unlikely partnership."),
d("Gu Family Book",2013,7.8,["Historical","Romance","Fantasy"],24,"1h 05m","Shin Woo-chul",["Lee Seung-gi","Bae Suzy"],"A half-human half-monster seeks to become fully human."),
d("Good Doctor",2013,8.0,["Medical","Drama","Romance"],20,"1h 10m","Ki Min-soo",["Joo Won","Moon Chae-won"],"An autistic surgical resident with savant syndrome tries to prove himself."),
d("Two Weeks",2013,7.9,["Action","Thriller","Drama"],16,"1h 10m","Oh Choong-hwan",["Lee Joon-gi","Park Ha-sun"],"An ordinary man must prove his innocence in two weeks while protecting his daughter."),
d("Empire of Gold",2013,7.7,["Drama","Political"],24,"1h 05m","Kim Young-ki",["Go Soo","Lee Yo-won"],"Three people fight for control of a massive conglomerate."),
d("Queen Inhyuns Man",2012,7.9,["Romance","Fantasy","Historical"],16,"1h 05m","Kim Won-seok",["Yoo In-na","Ji Hyun-woo"],"A Joseon scholar time-travels to modern Seoul and falls for an actress."),
d("Rooftop Prince",2012,8.0,["Romance","Fantasy","Comedy"],20,"1h 05m","Shin Yoon-ho",["Park Yoo-chun","Han Ji-min"],"A Joseon prince time-travels to modern Seoul and meets a woman who reminds him of his love."),
d("The Moon Embracing the Sun",2012,8.4,["Historical","Romance","Drama"],20,"1h 10m","Kim Do-hoon",["Kim Soo-hyun","Han Ga-in"],"A king and a female shaman overcome court intrigue in the Joseon dynasty."),
d("Bridal Mask",2012,8.5,["Historical","Action","Drama"],28,"1h 05m","Choo Sung-hwan",["Joo Won","Shin Se-kyung"],"A masked vigilante fights for Korean independence during the Japanese occupation."),
d("A Gentlemans Dignity",2012,7.6,["Romance","Comedy","Drama"],20,"1h 05m","Shin Woo-chul",["Jang Dong-gun","Kim Ha-neul"],"Four men in their 40s navigate love and professional challenges."),
d("Ghost",2012,7.8,["Thriller","Crime","Sci-Fi"],20,"1h 05m","Kim Sang-ho",["So Ji-sub","Lee Yeon-hee"],"A detective investigates cyber crimes uncovering a massive conspiracy."),
d("Missing You",2012,7.8,["Romance","Melodrama","Thriller"],21,"1h 10m","Lee Jae-dong",["Yoon Eun-hye","Yoochun"],"First loves reunite but a serial killer complicates their reunion."),
d("Dr. Jin",2012,7.5,["Sci-Fi","Historical","Medical"],22,"1h 05m","Han Hee",["Song Seung-heon","Park Min-young"],"A modern neurosurgeon travels back to the Joseon dynasty."),
d("Love Rain",2012,7.4,["Romance","Drama","Melodrama"],20,"1h 05m","Yoon Seok-ho",["Jang Keun-suk","Im Yoon-ah"],"Two generations of love stories intertwine as their children meet."),
d("I Do I Do",2012,7.6,["Romance","Comedy","Drama"],16,"1h 05m","Kang Min-soo",["Kim Sun-ah","Lee Jang-woo"],"A successful shoe designer gets pregnant and navigates single motherhood."),
d("History of a Salaryman",2012,7.8,["Comedy","Drama","Action"],24,"1h 05m","Kim Sang-ho",["Lee Sun-kyun","Jung Bo-suk"],"A salaryman infiltrates a rival company and gets caught in corporate espionage."),
d("Secret Garden",2010,8.1,["Romance","Fantasy","Comedy"],20,"1h 10m","Shin Woo-chul",["Hyun Bin","Ha Ji-won"],"A wealthy CEO and a stuntwoman magically swap bodies."),
d("Dong Yi",2010,8.2,["Historical","Drama","Romance"],60,"1h 05m","Lee Byung-hoon",["Han Hyo-joo","Ji Jin-hee"],"A humble woman rises to become the beloved consort of King Sukjong."),
d("Giant",2010,8.2,["Drama","Action"],60,"1h 05m","Yoo In-chul",["Lee Beom-soo","Jung Bo-suk"],"Three orphans rise from the slums of 1960s Seoul to power."),
d("Baker King Kim Tak Goo",2010,8.2,["Drama","Romance"],30,"1h 05m","Lee Joo-seung",["Yoon Shi-yoon","Jung Il-woo"],"An illegitimate son rises from poverty to become a master baker."),
d("Sungkyunkwan Scandal",2010,8.0,["Historical","Romance","Comedy"],20,"1h 10m","Kim Won-seok",["Park Yoo-chun","Park Min-young","Song Joong-ki"],"A woman disguises as a man to enter the all-male Confucian academy."),
d("City Hunter",2011,8.3,["Action","Romance","Thriller"],20,"1h 05m","Cha Tae-sung",["Lee Min-ho","Park Min-young"],"A man raised for revenge operates as a vigilante in modern Seoul."),
d("The Princess Man",2011,8.3,["Historical","Romance","Drama"],24,"1h 05m","Kim Jin-min",["Park Si-hoo","Moon Chae-won"],"A Romeo and Juliet romance in the Joseon dynasty."),
d("Tree with Deep Roots",2011,8.0,["Historical","Thriller","Mystery"],24,"1h 05m","Jang Tae-yoo",["Jang Hyuk","Han Suk-kyu"],"A detective investigates deaths during the creation of the Korean alphabet."),
d("Warrior Baek Dong-soo",2011,7.6,["Historical","Action","Drama"],29,"1h 05m","Lee Hyun-joo",["Ji Chang-wook","Yoo Ji-tae"],"The life of a martial artist who protected King Yeongjo."),
d("49 Days",2011,7.9,["Romance","Fantasy","Drama"],20,"1h 10m","Jo Nam-kook",["Nam Gyu-ri","Lee Yo-won"],"A comatose woman has 49 days to find three people who truly love her."),
d("Can You Hear My Heart",2011,8.0,["Romance","Drama"],30,"35m","Kim Young-ki",["Kim Jae-won","Hwang Jung-eum"],"A hearing-impaired man and a woman who cannot lie find healing."),
d("Padam Padam",2011,8.0,["Romance","Drama","Fantasy"],20,"1h 05m","Kim Chul-kyu",["Jung Woo-sung","Han Ji-min"],"An ex-convict and a veterinarian find love with a guardian angel."),
d("Three Brothers",2011,7.8,["Comedy","Drama","Family"],70,"35m","Kim Jung-gyu",["Ahn Nae-sang","Kim Dong-wan"],"Three very different brothers navigate life and family obligations."),
d("Brain",2011,7.7,["Medical","Drama"],20,"1h 05m","Jo Soo-won",["Shin Ha-kyun","Choi Jung-won"],"An arrogant neurosurgeon confronts his past and learns healing."),
d("Boys Over Flowers",2009,7.9,["Romance","Comedy","Drama"],25,"1h 10m","Jeon Ki-sang",["Lee Min-ho","Ku Hye-sun","Kim Hyun-joong"],"A poor girl gets into an elite school and catches the eye of F4 leader."),
d("IRIS",2009,7.9,["Action","Thriller","Romance"],20,"1h 10m","Kim Gyu-tae",["Lee Byung-hun","Kim Tae-hee"],"Two best friends discover a secret organization manipulating international relations."),
d("Brilliant Legacy",2009,7.8,["Drama","Romance"],28,"1h 05m","Jung Eul-young",["Han Hyo-joo","Lee Seung-gi"],"A kind woman loses everything and is taken in by a wealthy family."),
d("Queen Seondeok",2009,8.1,["Historical","Drama"],62,"1h 05m","Park Hong-gyu",["Lee Yo-won","Go Hyun-jung"],"The story of Queen Seondeok who overcame political intrigue to rule."),
d("Coffee Prince",2007,8.2,["Romance","Comedy"],17,"1h 05m","Lee Yoon-jung",["Gong Yoo","Yoon Eun-hye"],"A woman disguised as a man gets hired at an all-male coffee shop."),
d("Jewel in the Palace",2003,8.8,["Historical","Drama"],54,"1h 05m","Lee Byung-hoon",["Lee Young-ae","Ji Jin-hee"],"A girl rises to become the first female royal physician in Joseon."),
d("Full House",2004,7.8,["Romance","Comedy"],16,"1h 05m","Pyo Min-soo",["Rain","Song Hye-kyo"],"A screenwriter and an actor slowly fall in love while sharing a house."),
d("My Lovely Sam-soon",2005,8.2,["Romance","Comedy","Drama"],16,"1h 05m","Kim Yoon-chul",["Kim Sun-ah","Hyun Bin"],"A talented pastry chef and a chaebol heir fall in love."),
d("Lovers in Paris",2004,7.8,["Romance","Comedy","Drama"],20,"1h 05m","Shin Woo-chul",["Park Shin-yang","Kim Jung-eun"],"A housekeeper and a chaebol heir meet in Paris and fall in love."),
d("Stairway to Heaven",2003,7.9,["Romance","Drama","Melodrama"],20,"1h 05m","Choi Suk-bum",["Kwon Sang-woo","Choi Ji-woo"],"Childhood sweethearts are torn apart by fate and memory loss."),
d("Autumn in My Heart",2000,8.1,["Romance","Drama","Melodrama"],16,"1h 05m","Yoon Seok-ho",["Song Seung-heon","Song Hye-kyo"],"Two people switched at birth fall in love only to discover a devastating truth."),
d("Winter Sonata",2002,8.0,["Romance","Drama"],20,"1h 05m","Yoon Seok-ho",["Choi Ji-woo","Bae Yong-joon"],"A man loses his memory and forgets the woman he loved."),
d("Goong",2006,7.7,["Romance","Historical","Comedy"],24,"1h 05m","Hwang In-hyuk",["Yoon Eun-hye","Joo Ji-hoon"],"In an alternate Korea where monarchy still exists a girl marries the crown prince."),
d("East of Eden",2008,7.9,["Drama","Action","Melodrama"],50,"1h 05m","Kim Jin-soo",["Song Il-gook","Yeon Jung-hoon"],"Two friends grow up on opposite sides of the law in 1960s-80s Korea."),
d("My Girl",2005,7.7,["Romance","Comedy"],16,"1h 05m","Lee Jin-suk",["Lee Dong-gun","Lee Ji-ah"],"A con mans daughter and a chaebol heir are forced to be cousins and fall in love."),
d("Will It Snow for Christmas",2009,7.5,["Romance","Melodrama"],16,"1h 05m","Kim Won-seok",["Go Soo","Soo Ae"],"A couple falls in love during Christmas only to be separated by tragedy."),
d("Temptation of Wife",2008,7.6,["Drama","Melodrama"],129,"40m","Kim Young-soo",["Jang Seo-hee","Byun Woo-min"],"A woman presumed dead returns to seek revenge on her husband and his mistress."),
d("The World That They Live In",2008,7.3,["Romance","Drama"],16,"1h 05m","Kim Jin-seon",["Song Hye-kyo","Hyun Bin"],"A drama director and an assistant director navigate the TV industry and romance."),
d("Love Story in Harvard",2004,7.7,["Romance","Drama"],16,"1h 05m","Lee Hyung-min",["Kim Rae-won","Sunwoo Sun"],"Korean students at Harvard navigate love and cultural identity."),
d("Daljas Spring",2007,7.6,["Romance","Comedy"],22,"1h 05m","Lee Yun-jung",["Chae Rim","Lee Sun-kyun"],"A single career woman in her 30s navigates love and self-discovery."),
d("Golden Bride",2007,7.4,["Romance","Drama"],24,"1h 05m","Kim Nam-sung",["Choi Cheol-ho","Nam Sang-mi"],"A Vietnamese woman comes to Korea as a mail-order bride and struggles."),
d("Glory of the Family",2010,7.4,["Drama","Family"],50,"1h 05m","Kim Yoon-chul",["Shim Eun-ha","Lee Dong-wook"],"Two families from different social classes are bound by fate and relationships."),
d("Ojakgyo Brothers",2011,7.7,["Drama","Romance","Comedy"],50,"1h 05m","Jung Eul-young",["Jung Woo-sung","Uee"],"Three brothers on a farm navigate love and family feuds."),
d("Shut Up Flower Boy Band",2012,7.8,["Music","Youth","Drama"],16,"1h 05m","Lee Kwon",["Sung Joon","Lee Hyun-woo"],"High school misfits form a rock band and navigate fame and heartbreak."),
d("To the Beautiful You",2012,7.3,["Romance","Comedy","Youth"],12,"1h 05m","Cho Yong-kwang",["Choi Min-ho","Sulli"],"A girl disguises as a boy to attend an all-boys school."),
d("Glory Jane",2011,7.4,["Romance","Drama"],24,"1h 05m","Kang Min-soo",["Choi Siwon","Park Min-young"],"A woman discovers her true identity and navigates romance."),
d("Operation Proposal",2012,7.4,["Romance","Fantasy","Drama"],16,"1h 05m","Kim Won-seok",["Yoo In-na","Ji Hyun-woo"],"A man travels back in time to prevent his best friend marriage."),
d("Feast of the Gods",2012,7.6,["Drama","Food"],50,"1h 05m","Lee Hyung-min",["Seo Hyun-jin","Lee Sang-woo"],"A woman competes for the top position in traditional Korean food."),
d("Equator Man",2012,7.5,["Drama","Romance","Melodrama"],20,"1h 05m","Yoo Joong-seok",["Lee Joon-gi","Moon Chae-won"],"A blind man and a woman he once loved navigate revenge and redemption."),
d("The Night Watchman",2014,7.5,["Historical","Fantasy","Action"],24,"1h 05m","Kim Sang-ho",["Jung Il-woo","Go Woo-ri"],"Night watchers protect the Joseon dynasty from dark spirits."),
d("High School King of Savvy",2014,7.5,["Romance","Comedy","Youth"],17,"1h 10m","Kim Won-seok",["Seo In-guk","Lee Hye-ri"],"A high schooler impersonates his brother as a tech company executive."),
d("plus Nine Boys",2014,7.3,["Comedy","Drama","Family"],17,"1h 10m","Kim Sung-wook",["Yoo Oh-sung","Park Yoo-chun"],"Four men whose ages end in nine face major life changes."),
d("Discovery of Love",2014,7.4,["Romance","Drama"],16,"1h 10m","Lee Eon-hee",["Jung Yu-mi","Eric Mun"],"A furniture designer reconnects with her ex while dating a new man."),
d("What Happens to My Family",2014,7.9,["Comedy","Drama","Family"],53,"35m","Kim Hyung-il",["Kim Sang-kyung","Yoo Dong-geun"],"A patriarch tries to hold his dysfunctional family together."),
d("Liar Game",2014,7.6,["Thriller","Psychological","Drama"],12,"1h 10m","Choi Jung-bum",["Kim So-eun","Lee Sang-yoon"],"A college student and a con artist participate in a psychological game."),
d("A Korean Odyssey",2017,7.5,["Fantasy","Comedy","Romance"],20,"1h 20m","Park Hong-kyun",["Lee Seung-gi","Oh Yeon-seo"],"A modern reimagining of Journey to the West with a conman Monkey King."),
d("Voice",2017,7.9,["Crime","Thriller","Action"],16,"1h 05m","Kim Hong-sun",["Jang Hyuk","Lee Ha-na"],"An emergency call center team leader and a detective hunt a serial killer."),
d("Law School",2021,7.9,["Legal","Drama","Mystery"],16,"1h 10m","Kim Seong-wook",["Kim Myung-min","Ryu Hye-young"],"Students and professors at a law school are drawn into a murder investigation."),
d("River Where the Moon Rises",2021,7.4,["Historical","Romance","Action"],20,"1h 10m","Yoon Sang-ho",["Kim So-hyun","Ji Soo"],"The love story between Princess Pyeonggang and On-dal in the Goguryeo kingdom."),
d("Graceful Friends",2020,7.3,["Drama","Thriller"],17,"1h 10m","Yoon Sung-sik",["Yoo Jun-sang","Song Yoon-ah"],"Friends in their 40s face suspicion and betrayal when a murder occurs."),
d("Was It Love?",2020,7.2,["Romance","Comedy","Drama"],16,"1h 10m","Cho Hyun-taek",["Song Ji-hyo","Son Ho-jun"],"A single mother navigates romance with four very different men."),
d("Rugal",2020,7.2,["Action","Sci-Fi","Thriller"],16,"1h 10m","Kang Chul-woo",["Choi Jin-hyuk","Park Sung-woong"],"A detective gains cybernetic eyes to fight a criminal organization."),
d("True Beauty",2020,7.8,["Romance","Comedy","Drama"],16,"1h 10m","Kim Sang-hyeop",["Moon Ga-young","Cha Eun-woo","Hwang In-yeop"],"A girl who is a makeup goddess by day hides her bare face."),
d("Cheat on Me If You Can",2020,7.2,["Romance","Thriller","Comedy"],16,"1h 10m","Kim Soo-jin",["Go Joon","Cho Yeo-jeong"],"A divorce lawyer and his novelist wife suspect each other of infidelity."),
d("Love ft. Marriage and Divorce",2021,7.2,["Drama","Romance"],16,"1h 10m","Yoon Sung-sik",["Lee Tae-ran","Jeon Soo-kyeong"],"Three women deal with betrayal trust and reinvention in marriage."),
d("Your Honor",2018,7.6,["Drama","Thriller","Legal"],32,"35m","Yoon Sung-ho",["Namkoong Min","Chen"],"A judge must choose between conscience and protecting his criminal son."),
d("Sketch",2018,7.5,["Crime","Thriller","Fantasy"],16,"1h 10m","Lim Soon-ae",["Rain","Lee Sun-bin"],"A detective who sees the future through sketches hunts a serial killer."),
d("Matrimonial Chaos",2018,7.9,["Romance","Comedy"],32,"35m","Yoo Je-won",["Cha Tae-hyun","Bae Jong-ok"],"Two couples with opposing views on marriage navigate love and fidelity."),
d("Top Star Yoo Baek",2018,7.4,["Romance","Comedy"],16,"1h 10m","Park Jun-hwa",["Kim Ji-soo","Uee"],"A top actor gets sent to a remote island and meets an ordinary woman."),
d("Mama Fairy and the Woodcutter",2018,7.3,["Romance","Fantasy","Comedy"],16,"1h 10m","Kim Sang-hyun",["Yoon So-hee","Sung Yu-ri"],"A fairy descended as a crane falls in love with a modern barista."),
d("Flower Boy Ramyun Shop",2011,7.5,["Romance","Comedy","Youth"],16,"1h 05m","Hwang In-hyuk",["Jung Il-woo","Lee Chung-ah"],"A young woman inherits a ramyun shop surrounded by handsome young men."),
d("Beautiful Days",2016,7.4,["Romance","Drama"],20,"1h 10m","Lee Jae-dong",["Lee Joon-ki","Shin Se-kyung"],"A man and woman find healing and love during their darkest days."),
d("My Shy Boss",2017,7.3,["Romance","Comedy"],12,"1h 05m","Song Hyun-wook",["Yoon Hyun-min","Hwang Jung-eum"],"A painfully shy CEO and an enthusiastic employee misunderstand constantly."),
d("Welcome to Waikiki",2018,8.3,["Comedy","Drama"],20,"1h 10m","Lee Chang-min",["Kim Jung-hyun","Lee Yi-kyung","Son Seung-won"],"Friends struggling with careers run a guesthouse leading to hilarious situations."),
d("Wok of Love",2018,7.6,["Romance","Comedy","Food"],38,"35m","Park Jun-hwa",["Jang Hyuk","Jang Nara","Junho"],"A disgraced star chef finds redemption at a failing Chinese restaurant."),
d("Oh My Ghost",2015,7.9,["Romance","Comedy","Fantasy"],16,"1h 10m","Yoo Je-won",["Park Bo-young","Jo Jung-suk"],"A timid chef possessed by a ghost transforms into a confident cook."),
d("Reply 1997",2012,8.4,["Comedy","Romance","Drama"],16,"1h 10m","Shin Won-ho",["Jung Eun-ji","Seo In-guk"],"Six friends in Busan navigate K-pop fandom and first love in the 1990s."),
d("The Best Hit",2017,7.6,["Comedy","Music","Drama"],32,"35m","Yoon Sung-ho",["Kim Min-jae","Yoon Shi-yoon"],"A 90s pop star resurfaces 20 years later struggling to adapt."),
d("Let Me Be Your Knight",2021,7.3,["Romance","Comedy","Music"],18,"1h 05m","Ahn Ji-sook",["Jung Chae-yeon","Lee Jun-young"],"A sleepwalking doctor becomes a K-pop bands live-in physician."),
d("Reflection of You",2021,7.2,["Drama","Thriller"],16,"1h 05m","Lim Hyun-woo",["Go Hyun-jung","Shin Hyun-been"],"A successful painter faces a woman from her past seeking revenge."),
d("The Road: Tragedy of One",2021,7.3,["Drama","Thriller","Mystery"],14,"1h 10m","Kim No-won",["Ji Jin-hee","Yoon Se-ah"],"Residents of an exclusive complex hide dark secrets."),
d("Queen of the Office",2013,7.5,["Comedy","Drama"],16,"1h 10m","Kwon Sung-chan",["Kim Hye-soo","Jung Woong-in"],"A disgraced prosecutor becomes a temp worker and fights for justice."),
d("The Graduation Trip",2015,7.2,["Romance","Drama"],16,"1h 05m","Kim Hong-sun",["Yoon Shi-yoon","Cho Yoon-woo"],"College students on a graduation trip face life-changing decisions."),
d("The Hymn of Death",2018,8.3,["Historical","Romance","Melodrama"],6,"35m","Park Soo-jin",["Lee Jong-suk","Shin Hye-sun"],"A soprano and a playwright fall in love during the Japanese occupation."),
d("Love (ft. Marriage and Divorce)",2021,7.2,["Drama","Romance"],16,"1h 10m","Yoon Sung-sik",["Lee Tae-ran","Jeon Soo-kyeong"],"Three women deal with betrayal and reinvention in their marriages."),
];

// Build the export
const moviesData = kdramas.map(k => {
  const slug = k.title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  return {
    slug,
    title: k.title,
    year: k.year,
    rating: k.rating,
    genres: k.genres,
    episodes: k.episodes,
    runtime: k.runtime,
    language: 'Korean',
    director: k.director,
    cast: k.cast,
    plot: k.plot,
    trailerYouTubeId: '',
    category: 'kdrama',
  };
});

writeFileSync(
  join(__dirname, '..', 'src', 'lib', 'kdramas.json'),
  JSON.stringify(moviesData, null, 2)
);

console.log(`Written ${moviesData.length} K-dramas to src/lib/kdramas.json`);
